var express = require('express');
var router = express.Router();

var data_hot = {
    title:'按类别浏览产品',
    category:[
      { title:"北京",
        url:"/page/2421",
        list:[
          { product_img:"/resource/1001",
            price:128.80,
            star:2,
            grade_num:129,
            desc:"自然和谐的体验",
            info:"wifi很快",
            owner_img:"/resource/1001",
            owner_name:"老张",
            label:["标签","开始"],
            reminder:"吐血大甩卖",
            url:'/page/0'
          },
          { product_img:"/resource/1002",
            price:128.80,
            star:3,
            grade_num:129,
            desc:"自然和谐的体验",
            info:"wifi很快",
            owner_img:"/resource/1002",
            owner_name:"老张",
            label:[],
            reminder:"",
            url:'/page/0'
          },
          { product_img:"/resource/1003",
            price:128.80,
            star:0,
            grade_num:129,
            desc:"自然和谐的体验",
            info:"wifi很快",
            owner_img:"/resource/1003",
            owner_name:"老张",
            label:[],
            reminder:"",
            url:'/page/0'
          },
          { product_img:"/resource/1004",
            price:128.80,
            star:4,
            grade_num:129,
            desc:"自然和谐的体验",
            info:"wifi很快",
            owner_img:"/resource/1004",
            owner_name:"老张",
            label:[],
            reminder:"",
            url:'/page/0'
          },
          { product_img:"/resource/1005",
            price:128.80,
            star:4,
            grade_num:129,
            desc:"自然和谐的体验",
            info:"wifi很快",
            owner_img:"/resource/1005",
            owner_name:"老张",
            label:["标签标签标签"],
            reminder:"吐血大甩卖",
            url:'/page/0'
          },
          { product_img:"/resource/1006",
            price:128.80,
            star:4,
            grade_num:129,
            desc:"自然和谐的体验",
            info:"wifi很快",
            owner_img:"/resource/1006",
            owner_name:"老张",
            label:[],
            reminder:"吐血大甩卖",
            url:'/page/0'
          }
        ]
      },
      { title:"上海",
        url:"/page/2421",
        list:[
          { product_img:"/resource/1007",
            price:128.80,
            star:4,
            grade_num:129,
            desc:"自然和谐的体验",
            info:"wifi很快",
            owner_img:"/resource/1007",
            owner_name:"老张",
            label:[],
            reminder:"",
            url:'/page/0'
          },
          { product_img:"/resource/1008",
            price:128.80,
            star:4,
            grade_num:129,
            desc:"自然和谐的体验",
            info:"wifi很快",
            owner_img:"/resource/1008",
            owner_name:"老张",
            label:["标签标签标签"],
            reminder:"",
            url:'/page/0'
          },
          { product_img:"/resource/1009",
            price:128.80,
            star:4,
            grade_num:129,
            desc:"自然和谐的体验",
            info:"wifi很快",
            owner_img:"/resource/1009",
            owner_name:"老张",
            label:[],
            reminder:"",
            url:'/page/0'
          },
          { product_img:"/resource/1010",
            price:128.80,
            star:4,
            grade_num:129,
            desc:"自然和谐的体验",
            info:"wifi很快",
            owner_img:"/resource/1010",
            owner_name:"老张",
            label:["标签标签标签"],
            reminder:"吐血大甩卖",
            url:'/page/0'
          },
          { product_img:"/resource/1001",
            price:128.80,
            star:4,
            grade_num:129,
            desc:"自然和谐的体验",
            info:"wifi很快",
            owner_img:"/resource/1001",
            owner_name:"老张",
            label:[],
            reminder:"",
            url:'/page/0'
          },
          { product_img:"/resource/1002",
            price:128.80,
            star:4,
            grade_num:129,
            desc:"自然和谐的体验",
            info:"wifi很快",
            owner_img:"/resource/1002",
            owner_name:"老张",
            label:[],
            reminder:"吐血大甩卖",
            url:'/page/0'
          }
        ]
      },
      { title:"洛杉矶",
        url:"/page/2421",
        list:[
          { product_img:"/resource/1003",
            price:128.80,
            star:4,
            grade_num:129,
            desc:"自然和谐的体验",
            info:"wifi很快",
            owner_img:"/resource/1003",
            owner_name:"老张",
            label:[],
            reminder:"",
            url:'/page/0'
          },
          { product_img:"/resource/1004",
            price:128.80,
            star:4,
            grade_num:129,
            desc:"自然和谐的体验",
            info:"wifi很快",
            owner_img:"/resource/1004",
            owner_name:"老张",
            label:[],
            reminder:"",
            url:'/page/0'
          },
          { product_img:"/resource/1005",
            price:128.80,
            star:4,
            grade_num:129,
            desc:"自然和谐的体验",
            info:"wifi很快",
            owner_img:"/resource/1005",
            owner_name:"老张",
            label:[""],
            reminder:"",
            url:'/page/0'
          },
          { product_img:"/resource/1006",
            price:128.80,
            star:4,
            grade_num:129,
            desc:"自然和谐的体验",
            info:"wifi很快",
            owner_img:"/resource/1006",
            owner_name:"老张",
            label:[],
            reminder:"",
            url:'/page/0'
          },
          { product_img:"/resource/1007",
            price:128.80,
            star:4,
            grade_num:129,
            desc:"自然和谐的体验",
            info:"wifi很快",
            owner_img:"/resource/1007",
            owner_name:"老张",
            label:["标签标签标签"],
            reminder:"吐血大甩卖",
            url:'/page/0'
          },
          { product_img:"/resource/1008",
            price:128.80,
            star:4,
            grade_num:129,
            desc:"自然和谐的体验",
            info:"wifi很快",
            owner_img:"/resource/1008",
            owner_name:"老张",
            label:[""],
            reminder:"",
            url:'/page/0'
          }
        ]
      },
      { title:"廊坊",
        url:"/page/2421",
        list:[
          { product_img:"/resource/1009",
            price:128.80,
            star:4,
            grade_num:129,
            desc:"自然和谐的体验",
            info:"wifi很快",
            owner_img:"/resource/1009",
            owner_name:"老张",
            label:[""],
            reminder:"吐血大甩卖",
            url:'/page/0'
          },
          { product_img:"/resource/1010",
            price:128.80,
            star:4,
            grade_num:129,
            desc:"自然和谐的体验",
            info:"wifi很快",
            owner_img:"/resource/1010",
            owner_name:"老张",
            label:["标签标签标签"],
            reminder:"",
            url:'/page/0'
          },
          { product_img:"/resource/1001",
            price:128.80,
            star:4,
            grade_num:129,
            desc:"自然和谐的体验",
            info:"wifi很快",
            owner_img:"/resource/1001",
            owner_name:"老张",
            label:[],
            reminder:"",
            url:'/page/0'
          },
          { product_img:"/resource/1002",
            price:128.80,
            star:4,
            grade_num:129,
            desc:"自然和谐的体验",
            info:"wifi很快",
            owner_img:"/resource/1002",
            owner_name:"老张",
            label:["标签标签标签"],
            reminder:"吐血大甩卖",
            url:'/page/0'
          },
          { product_img:"/resource/1003",
            price:128.80,
            star:4,
            grade_num:129,
            desc:"自然和谐的体验",
            info:"wifi很快",
            owner_img:"/resource/1003",
            owner_name:"老张",
            label:[""],
            reminder:"",
            url:'/page/0'
          },
          { product_img:"/resource/1004",
            price:128.80,
            star:4,
            grade_num:129,
            desc:"自然和谐的体验",
            info:"wifi很快",
            owner_img:"/resource/1004",
            owner_name:"老张",
            label:["标签标签标签"],
            reminder:"吐血大甩卖",
            url:'/page/0'
          }
        ]
      },
    ]
  };

var data_explore = {
    title:'冒险乐园',
    content:[
      { product_img:"/resource/1001",
        price:128.80,
        star:2,
        grade_num:129,
        desc:"自然和谐的体验",
        info:"张家口",
        owner_img:"/resource/1001",
        owner_name:"老张",
        label:["标签","开始"],
        reminder:"吐血大甩卖",
        url:'/page/0'
      },
      { product_img:"/resource/1008",
        price:128.80,
        star:4,
        grade_num:129,
        desc:"自然和谐的体验",
        info:"成都",
        owner_img:"/resource/1008",
        owner_name:"老张",
        label:["标签标签标签"],
        reminder:"",
        url:'/page/0'
      },
      { product_img:"/resource/1003",
        price:128.80,
        star:4,
        grade_num:129,
        desc:"自然和谐的体验",
        info:"马六甲",
        owner_img:"/resource/1003",
        owner_name:"老张",
        label:[""],
        reminder:"",
        url:'/page/0'
      },
      { product_img:"/resource/1006",
        price:128.80,
        star:4,
        grade_num:129,
        desc:"自然和谐的体验",
        info:"太子港",
        owner_img:"/resource/1006",
        owner_name:"老张",
        label:[""],
        reminder:"",
        url:'/page/0'
      },
      { product_img:"/resource/1004",
        price:128.80,
        star:4,
        grade_num:129,
        desc:"自然和谐的体验",
        info:"库伦",
        owner_img:"/resource/1004",
        owner_name:"老张",
        label:["标签标签标签"],
        reminder:"吐血大甩卖",
        url:'/page/0'
      },
      { product_img:"/resource/1007",
        price:128.80,
        star:4,
        grade_num:129,
        desc:"自然和谐的体验",
        info:"基督城",
        owner_img:"/resource/1007",
        owner_name:"老张",
        label:["标签标签标签"],
        reminder:"吐血大甩卖",
        url:'/page/0'
      }
    ]
  };

var data_recent = {
    title:'最近浏览过的',
    content:[
      { product_img:"/resource/1001",
        price:128.80,
        star:2,
        grade_num:129,
        desc:"自然和谐的体验",
        info:"wifi很快",
        owner_img:"/resource/1001",
        owner_name:"老张",
        label:["标签","开始"],
        reminder:"吐血大甩卖",
        url:'/page/0'
      },
      { product_img:"/resource/1008",
        price:128.80,
        star:4,
        grade_num:129,
        desc:"自然和谐的体验",
        info:"wifi很快",
        owner_img:"/resource/1008",
        owner_name:"老张",
        label:["标签标签标签"],
        reminder:"",
        url:'/page/0'
      },
      { product_img:"/resource/1003",
        price:128.80,
        star:4,
        grade_num:129,
        desc:"自然和谐的体验",
        info:"wifi很快",
        owner_img:"/resource/1003",
        owner_name:"老张",
        label:[""],
        reminder:"",
        url:'/page/0'
      },
      
    ]
  };

var hot = function (param){
    return JSON.parse(JSON.stringify(data_hot));
}
var explore = function (param){
    return JSON.parse(JSON.stringify(data_explore));
}
var recent = function (param){
    return JSON.parse(JSON.stringify(data_recent));
}
/*Get*/
router.get('/hot', function(req, res, next) {
  res.json(hot());
});

router.get('/explore', function(req, res, next) {
  res.json(explore());
});

router.get('/recent', function(req, res, next) {
  res.json(recent());
});

var exp = {router,hot,explore,recent};

module.exports = router;
